#!/bin/bash
function fe() {
	PS3="Select a repo: "
	select opt in fev1 fev2 configstudio quit; do
		case $opt in
		fev1)
			PS3="Select a mode for FEV1: "
			select mode in watch host install build quit; do
				case $mode in
				watch)
					echo "Starting watch mode in FEV1"
					nvm_switch old
					cd $REPO_ROOT/socotra-stack/source/stack-app-static || exit
					npm run watch
					;;
				host)
					echo "Starting host mode in FEV1"
					export TENANT_HOSTNAME=dclark27-admin-configeditor.co.develop.socotra.com
					export API_URL=api.develop.socotra.com
					export PORT=8080
					export LOAD_ASSETS_URL=https://studio.develop.socotra.com
					nvm_switch old
					cd $REPO_ROOT/socotra-stack/source/stack-app-static || exit
					npm run start
					;;
				install)
					echo "Installing FEV1"
					nvm_switch old
					cd $REPO_ROOT/socotra-stack/source/stack-app-static || exit
					npm install
					;;
				build)
					echo "Building FEV1"
					nvm_switch old
					cd $REPO_ROOT/socotra-stack/source/stack-app-static || exit
					npm run build
					;;
				quit)
					break
					;;
				*)
					echo "Invalid option"
					;;
				esac
			done
			;;
		fev2)
			PS3="Select a mode for FEV2: "
			select mode in start minikube_start install quit; do
				case $mode in
				start)
					echo "Starting FEV2"
					nvm use stable
					export API_URL=https://api.develop.socotra.com
					export LOAD_ASSETS_URL=https://studio.develop.socotra.com
					cd $REPO_ROOT/frontend-v2 || exit
					npm run start
					;;
				minikube_start)
					echo "Starting FEV2 in minikube env"
					nvm use stable
					export KEYCLOAK_URL=https://keycloak.minikube/auth/
					export TENANT_HOSTNAME=minikube-configeditor.co.minikube
					export API_URL=http://host.default:8080
					export LOAD_ASSETS_URL=http://host.default:8080

					cd $REPO_ROOT/frontend-v2 || exit
					npm run start:minikube
					;;
				install)
					echo "Installing FEV2"
					cd $REPO_ROOT/frontend-v2 || exit
					npm install
					;;
				quit)
					break
					;;
				*)
					echo "Invalid option"
					;;
				esac
			done
			;;
		configstudio)
			PS3="Select a mode for config studio: "
			select mode in start build-assets install quit; do
				case $mode in
				start)
					echo "Starting config studio"
					nvm_switch old
					export API_URL=api.develop.socotra.com
					export NODE_ENV=development
					cd $REPO_ROOT/socotra-stack/source/stack-config-manager || exit
					npm run start-dev
					;;
				build-assets)
					echo "Create config studio assets"
					nvm_switch old
					cd $REPO_ROOT/socotra-stack/source/stack-config-manager || exit
					npm run create-assets
					;;
				install)
					echo "Installing config studio"
					nvm_switch old
					cd $REPO_ROOT/socotra-stack/source/stack-config-manager || exit
					npm install
					;;
				quit)
					break
					;;
				*)
					echo "Invalid option"
					;;
				esac
			done
			;;
		quit)
			break
			;;
		*)
			echo "Invalid option $REPLY"
			;;
		esac
	done
}
